### ISSUE TITLE
[Request] KernelSU support for this and future phone models. 

### ISSUE THREAD

**Issue by Marucins** [NothingOSS/android_kernel_msm-5.4_nothing_sm7325#8]
Hi 
I don't hide the fact that I dislike artificial limitations. Android has always been associated with a certain kind of freedom to me. And it's in that direction that I believe Nothing Phone will be heading.

The current top-down system changes and restrictions imposed by Google for new applications are causing Magisk, the root application, to be increasingly detected by various banking software. There is an interesting alternative - KernelSU. Are you considering introducing support for this type of solution?

**Comment by TadiT7** [comment]
This is a device with permanently provisioned secure boot. The bootloader could be open source and replaceable by user otherwise. Additionally, it ships with GMS, that results in enforcing policies like this. They made this choice. It is not a poweruser friendly device, it's just ambiguous marketing trying to unjustifiably bring back the memories of early OP. You may need to wait a lot to even get the firehose file and any way to unbrick at home. If you buy it, you've been warned. Good luck with even getting repo maintainer's reply.

**Comment by sonnar0486** [comment]
This is a terrible idea. You should ask this from someone who make custom kernels, not them.
No one is stopping you though since it's open source and anyone who have the skills can modify it and you may get what you want.

**Comment by Marucins** [comment]
You're right. It's not a good phone for such openness. I need to look for something else.

**Comment by nitanmarcel** [comment]
KernelSU for any kernel lower than 5.9 is useless anyway as umount it's not working at all due to missing kernel functionality, there is a module to fix that but you would be better using Magisk or Magisk Delta (which has improved hiding)
